config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    puts "############  params: #{params[:page]} ##########"
    @articles = Article.order(id: :asc).page(params[:page]).per(5)
    if (@articles.count == 0)
      @articles = Article.order(id: :asc).page(params[:page].to_i - 1).per(5)
    end
    @article  = Article.new
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        puts "########### article ID: #{@article.id} #######"
        format.js { render layout: false }
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js {render layout: false }
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.js { render layout: false }
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.js { render layout: false }
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_row.html.haml
%tr
  %td= link_to article.title, article
  %td= truncate article.content, length: 32
  %td= link_to 'Edit', edit_article_path(article), remote: true
  %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, remote: true
  %td= article.id

app/views/articles/_form.html.haml
= form_for @article, remote: true do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/articles/_indexor.html.haml
%h1 Listing articles
%table
  %thead
    %tr
      %th Title
      %th Content
      %th
      %th
      %th ID
  %tbody#table_rows
    - @articles.each do |article|
      = render partial: "article_row", locals: {article: article}
%br

app/views/articles/_paginate.html.haml
= paginate @articles, window: 2, remote: true
= page_entries_info @articles
= link_to "update view", articles_path(page: @articles.current_page), remote: true, id: "update_view", hidden: true

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
#paginator= render 'paginate'
#indexor= render 'indexor'
%p#form_title New
#article_form= render 'form'

app/views/articles/new.html.haml
%h1 New article
= render 'form'
= link_to 'Back', articles_path
%br

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Content:
  = @article.content

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', :back
\|
= link_to 'Index', articles_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title TestAjaxRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    #ajax
    = yield